/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ncxlkhvlskwkksukgcyo"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jeGxraHZsc2t3a2tzdWtnY3lvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0Nzk5NTUsImV4cCI6MjA3ODA1NTk1NX0.OD-8kCOtcRzGiMRpUbqyiwdikAAXFF-AZqWn9z3It24"